### ISSUE TITLE
Satellite 6.8 API endpoint has changed

### ISSUE THREAD

**Issue by eppini** [puppetlabs/puppetlabs-satellite_pe_tools#138]
Satellite API enpoint was changed from /reports to /config_reports. 
url should be changed in lib/puppet/reports/satellite.rb

 submit_request '/api/reports', body ->  submit_request '/api/config_reports', body

**Comment by ekohl** [comment]
FYI: `/config_reports` was introduced a long time ago and `/reports` was deprecated then. All currently supported Satellite versions should have `/config_reports`.

**Comment by carabasdaniel** [comment]
Closed by: https://github.com/puppetlabs/puppetlabs-satellite_pe_tools/pull/139
