### ISSUE TITLE
provide ability to filter reports based on a fact

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-satellite_pe_tools#184]
## Use Case
I have discovered that Satellite server creates hosts entries for every single report sent, Windows, Solaris, Amazon Linux and so on

## Describe the Solution You Would Like
Provide capability to limit scope of the reports to a fact, for example os.name="RedHat"

## Describe Alternatives You've Considered
I have not find an option to ignore reports for not registered hosts in Satellite, they become registered the moment report is sent

**Comment by ekohl** [comment]
Perhaps not entirely what you're looking for, but there's a setting `Create new host when facts are uploaded` which defaults to yes. Since you probably already registered all RHEL machines, would that be sufficient?

**Comment by vchepkov** [comment]
Ah, and adjacent option `Create new host when report is uploaded`, thanks for the tip
