### ISSUE TITLE
Instructions in 4b are incorrect for Satellite 6.2

### ISSUE THREAD

**Issue by beergeek** [puppetlabs/puppetlabs-satellite_pe_tools#36]
In Satellite 6.2 the `capsule-certs-generate` command generate `rpm` files under the `~/ssl-build` directory, not cert or key files.

**Comment by pmcmaw** [comment]
Looking at the README I can see this issue has been resolved at some point as it now states:

`This creates a new folder: ~/ssl-build. This may contain either raw .crt and .key file, or a number of RPM files.`

Closing this issue, if you disagree with this solution please feel free to reopen.
 Also on a side note I would like to thank you for your patience for this resolution.
